### ISSUE TITLE
Terrain class implementation

### ISSUE THREAD

**Issue by TyrealGray** [SkyHarp/LegendOfMountainSea#40]
- [x] Terrain should be the children of stage

~~All other character and pattern should be the children of terrain~~

- [x] Terrain should render as hexagon side by side

- [x] A star navigation algorithm.

Nice to have:
- Bottom hexagons should be a litter bigger than top in order to make player feel a little 3D-visualized

**Example:**
![](https://i.imgur.com/r9X6XZK.jpg)

**Comment by Zweib** [comment]
I will try to implement this :D

**Comment by TyrealGray** [comment]
Example about how to implement **Nice to have** feature
http://pixijs.github.io/examples/#/projection/plane.js

**Comment by TyrealGray** [comment]
I checked the implementation yesterday, it seems this approach is relying on so many factor and not  good for pathfinding algorithm later on.

I will say we need to start to find new solution for this feature.

**Comment by Zweib** [comment]
Maybe pixi-projection will have too many limitations to be used?

**Comment by markx** [comment]
I'm trying to understand the game structure here. Are we moving all actors into the terrain? If not, then terrain is just a special actor in the stage, right?

**Comment by TyrealGray** [comment]
@markx All the characters have to go into terrain container, it's easy to manage if screen is move.
But character does not need to attach to hexagon grid.

**Comment by TyrealGray** [comment]
@Zweib I found out pixi-projection will not work within nw.js client.
